baseURL = "https://vadrouilles.co/"
languageCode = "en-us"
title = "🌲 Vadrouilles & Co."
theme = "less"
googleAnalytics = "UA-114349967-1"
disqusShortname = "vadrouilles-co"
[permalinks]
  wanders = "/:slug"
  notes = "/:slug"
[imaging]
  resampleFilter = "lanczos"
